[phases.build]
cmds = [
  "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache storage/framework/testing storage/logs bootstrap/cache",
  "chmod -R 777 storage bootstrap/cache",
  "composer install --no-dev --optimize-autoloader",
  "npm ci && npm run build"
]

[start]
cmd = "chmod +x /app/start.sh && /app/start.sh"
